site_name: XTS documentation
theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - navigation.top
    - navigation.instant
    - navigation.footer
  font: false
  logo: assets/logo.png

nav:
  - Home: index.md
  - Introduction:
    - About XTS: introduction/index.md
    - Hello, world!: introduction/helloworld.md
  - Manual:
    - How to write the layout file: manual/layoutxml.md
    - Structure of the data file: manual/structuredatafile.md
    - Placing objects: manual/outputtingobjects.md
    - Grid: manual/grid.md
    - Positioning areas: manual/positioningarea.md
    - File organization: manual/fileorganization.md
    - XPath and layout functions: manual/xpath.md
    - Using fonts: manual/fonts.md
    - CSS and HTML: manual/csshtml.md
    - Programming:
      - Introduction: manual/programming/index.md
      - Functions: manual/programming/functions.md
    - Preprocessing / Lua filter: manual/luafilter.md
    - Command line: manual/commandline.md
    - Configuration file: manual/configuration.md
    - Assigning a Schema to the Layout XML:
      - Overview: manual/assignschema/index.md
      - Visual Studio Code: manual/assignschema/vscode.md
      - Oxygen XML: manual/assignschema/oxygenxml.md
  - Reference:
    - Defaults: reference/defaults.md
    - Installation: reference/installation.md
    - Command reference:
      - Overview: reference/cmdreference/index.md
      - A: reference/cmdreference/a.md
      - Action: reference/cmdreference/action.md
      - AtPageCreation: reference/cmdreference/atpagecreation.md
      - AtPageShipout: reference/cmdreference/atpageshipout.md
      - Attribute: reference/cmdreference/attribute.md
      - B: reference/cmdreference/b.md
      - Barcode: reference/cmdreference/barcode.md
      - Bookmark: reference/cmdreference/bookmark.md
      - Box: reference/cmdreference/box.md
      - Br: reference/cmdreference/br.md
      - Case: reference/cmdreference/case.md
      - Circle: reference/cmdreference/circle.md
      - Clearpage: reference/cmdreference/clearpage.md
      - Column: reference/cmdreference/column.md
      - Columns: reference/cmdreference/columns.md
      - Contents: reference/cmdreference/contents.md
      - DefineColor: reference/cmdreference/definecolor.md
      - DefineMasterpage: reference/cmdreference/definemasterpage.md
      - Element: reference/cmdreference/element.md
      - ForAll: reference/cmdreference/forall.md
      - Function: reference/cmdreference/function.md
      - Group: reference/cmdreference/group.md
      - I: reference/cmdreference/i.md
      - Image: reference/cmdreference/image.md
      - Index: reference/cmdreference/index.md
      - Layout: reference/cmdreference/layout.md
      - Li: reference/cmdreference/li.md
      - Loaddataset: reference/cmdreference/loaddataset.md
      - Loop: reference/cmdreference/loop.md
      - Mark: reference/cmdreference/mark.md
      - Message: reference/cmdreference/message.md
      - NextFrame: reference/cmdreference/nextframe.md
      - NextRow: reference/cmdreference/nextrow.md
      - Ol: reference/cmdreference/ol.md
      - Options: reference/cmdreference/options.md
      - Otherwise: reference/cmdreference/otherwise.md
      - Pageformat: reference/cmdreference/pageformat.md
      - Paragraph: reference/cmdreference/paragraph.md
      - Param: reference/cmdreference/param.md
      - PDFOptions: reference/cmdreference/pdfoptions.md
      - PlaceObject: reference/cmdreference/placeobject.md
      - PositioningArea: reference/cmdreference/positioningarea.md
      - PositioningFrame: reference/cmdreference/positioningframe.md
      - ProcessNode: reference/cmdreference/processnode.md
      - Record: reference/cmdreference/record.md
      - SaveDataset: reference/cmdreference/savedataset.md
      - SetGrid: reference/cmdreference/setgrid.md
      - SetVariable: reference/cmdreference/setvariable.md
      - Span: reference/cmdreference/span.md
      - Stylesheet: reference/cmdreference/stylesheet.md
      - Switch: reference/cmdreference/switch.md
      - Table: reference/cmdreference/table.md
      - Tablehead: reference/cmdreference/tablehead.md
      - Td: reference/cmdreference/td.md
      - Textblock: reference/cmdreference/textblock.md
      - Tr: reference/cmdreference/tr.md
      - U: reference/cmdreference/u.md
      - Ul: reference/cmdreference/ul.md
      - Until: reference/cmdreference/until.md
      - Trace: reference/cmdreference/trace.md
      - Value: reference/cmdreference/value.md
      - While: reference/cmdreference/while.md


repo_url: https://github.com/speedata/xts

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - toc:
        permalink: "#"

plugins:
  - glightbox
  - include-markdown
  - search:
      lang: en

extra_css:
  - stylesheets/extra.css
  - stylesheets/monofont.css
  # - stylesheets/sansfont.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/mastodon
      link: https://typo.social/@speedata
  analytics:
    # provider: custom

copyright: Copyright 2023 speedata GmbH, Berlin (Germany)

# pip3 install mkdocs
# pip3 install mkdocs-material
# pip3 install mkdocs-glightbox
# pip3 install mkdocs-include-markdown-plugin

